use masterchef;
insert into Ingredients (nom_ingredient, type_ingredient, date_peremption_ingredient) values ('Tomate', 'Longue conserv', NULL);
insert into Ingredients (nom_ingredient, type_ingredient, date_peremption_ingredient) values ('Pâte à pizza', 'Frais', '08/12/2018');
insert into Ingredients (nom_ingredient, type_ingredient, date_peremption_ingredient) values ('Mozarella', 'Frais', '08/12/2018');
insert into Ingredients (nom_ingredient, type_ingredient, date_peremption_ingredient) values ('Piment d''espelette', 'Longue conserv', NULL);
insert into Recettes (nom_recette, temps_cuisson_recette, temps_preparation_recette) values ('Pizza', 10, 20);
insert into Composition (id_recette, id_ingredient, quantite_ingredient_recette) values (1, 2, 1);
insert into Composition (id_recette, id_ingredient, quantite_ingredient_recette) values (1, 1, 5);
insert into Composition (id_recette, id_ingredient, quantite_ingredient_recette) values (1, 3, 2);
insert into Materiel (nom_materiel, type_materiel, etat_materiel, quantite_materiel) values ('Fourchette', 'Matériel commun', 'Propre', 150);
insert into Materiel (nom_materiel, type_materiel, etat_materiel, quantite_materiel) values ('Couteau', 'Matériel commun', 'Propre', 150);
insert into Materiel (nom_materiel, type_materiel, etat_materiel, quantite_materiel) values ('Cuillère', 'Matériel commun', 'Propre', 150);
insert into Materiel (nom_materiel, type_materiel, etat_materiel, quantite_materiel) values ('Cuitochette', 'Matériel commun', 'Sale', 150);
insert into Materiel (nom_materiel, type_materiel, etat_materiel, quantite_materiel) values ('Table', 'Matériel de restauration', 'Propre', 5);
insert into Materiel (nom_materiel, type_materiel, etat_materiel, quantite_materiel) values ('Casserole', 'Matériel de cuisine', 'Propre', 2);
insert into Materiel (nom_materiel, type_materiel, etat_materiel, quantite_materiel) values ('Casserole', 'Matériel de cuisine', 'Sale', 5);
insert into Machines (nom_machine, etat_machine) values ('Four', 'Vide');
insert into Machines (nom_machine, etat_machine) values ('Micro-ondes', 'Vide');
insert into Machines (nom_machine, etat_machine) values ('Machine à pain', 'Vide');
insert into Machines (nom_machine, etat_machine) values ('Frigo', 'Plein');