use masterchef;




-- Remplissage table Recettes --

INSERT INTO Recettes (nom_recette, temps_cuisson_recette, temps_repos_recette, temps_preparation_recette, nombre_parts, type_recette) VALUES ('Feuilleté au crabe', 20, 0, 10, 4, 'Entrée');
INSERT INTO Recettes (nom_recette, temps_cuisson_recette, temps_repos_recette, temps_preparation_recette, nombre_parts, type_recette) VALUES ('Oeufs cocotte', 5, 0, 10, 4, 'Entrée');
INSERT INTO Recettes (nom_recette, temps_cuisson_recette, temps_repos_recette, temps_preparation_recette, nombre_parts, type_recette) VALUES ('Gaspatcho', 0, 0, 0, 4, 'Entrée');
INSERT INTO Recettes (nom_recette, temps_cuisson_recette, temps_repos_recette, temps_preparation_recette, nombre_parts, type_recette) VALUES ('Pâté de sanglier', 15, 20, 20, 10, 'Entrée');
INSERT INTO Recettes (nom_recette, temps_cuisson_recette, temps_repos_recette, temps_preparation_recette, nombre_parts, type_recette) VALUES ('Tarte au thon', 20, 0, 10, 6, 'Entrée');
INSERT INTO Recettes (nom_recette, temps_cuisson_recette, temps_repos_recette, temps_preparation_recette, nombre_parts, type_recette) VALUES ('Quiche Loraine', 35, 0, 15, 10, 'Entrée');
INSERT INTO Recettes (nom_recette, temps_cuisson_recette, temps_repos_recette, temps_preparation_recette, nombre_parts, type_recette) VALUES ('Foie Gras', 0, 0, 10, 1, 'Entrée');
INSERT INTO Recettes (nom_recette, temps_cuisson_recette, temps_repos_recette, temps_preparation_recette, nombre_parts, type_recette) VALUES ('Soupe chinoise', 30, 0, 15, 4, 'Entrée');
INSERT INTO Recettes (nom_recette, temps_cuisson_recette, temps_repos_recette, temps_preparation_recette, nombre_parts, type_recette) VALUES ('Les Cagouilles à la Charentaise', 20, 0, 30, 4, 'Entrée');
INSERT INTO Recettes (nom_recette, temps_cuisson_recette, temps_repos_recette, temps_preparation_recette, nombre_parts, type_recette) VALUES ('Macédoine', 0, 0, 20, 8, 'Entrée');
INSERT INTO Recettes (nom_recette, temps_cuisson_recette, temps_repos_recette, temps_preparation_recette, nombre_parts, type_recette) VALUES ('Bouillinade d''anguilles ou de poisson', 20, 0, 10, 4, 'Plat');
INSERT INTO Recettes (nom_recette, temps_cuisson_recette, temps_repos_recette, temps_preparation_recette, nombre_parts, type_recette) VALUES ('Boles de picolats', 0, 0, 60, 25, 'Plat');
INSERT INTO Recettes (nom_recette, temps_cuisson_recette, temps_repos_recette, temps_preparation_recette, nombre_parts, type_recette) VALUES ('Blanquette de veau', 20, 0, 10, 5, 'Plat');
INSERT INTO Recettes (nom_recette, temps_cuisson_recette, temps_repos_recette, temps_preparation_recette, nombre_parts, type_recette) VALUES ('Patte de porc', 60, 0, 30, 3, 'Plat');
INSERT INTO Recettes (nom_recette, temps_cuisson_recette, temps_repos_recette, temps_preparation_recette, nombre_parts, type_recette) VALUES ('Blanc de poulet crème et miel', 10, 0, 5, 2, 'Plat');
INSERT INTO Recettes (nom_recette, temps_cuisson_recette, temps_repos_recette, temps_preparation_recette, nombre_parts, type_recette) VALUES ('Escargots à la Catalane', 60, 0, 15, 4, 'Plat');
INSERT INTO Recettes (nom_recette, temps_cuisson_recette, temps_repos_recette, temps_preparation_recette, nombre_parts, type_recette) VALUES ('Chorba', 35, 0, 15, 4, 'Plat');
INSERT INTO Recettes (nom_recette, temps_cuisson_recette, temps_repos_recette, temps_preparation_recette, nombre_parts, type_recette) VALUES ('Tagliatelles au saumon fumé', 10, 0, 20, 4, 'Plat');
INSERT INTO Recettes (nom_recette, temps_cuisson_recette, temps_repos_recette, temps_preparation_recette, nombre_parts, type_recette) VALUES ('Pâtes carbonara', 15, 0, 5, 4, 'Plat');
INSERT INTO Recettes (nom_recette, temps_cuisson_recette, temps_repos_recette, temps_preparation_recette, nombre_parts, type_recette) VALUES ('Lasagnes', 60, 0, 30, 10, 'Plat');
INSERT INTO Recettes (nom_recette, temps_cuisson_recette, temps_repos_recette, temps_preparation_recette, nombre_parts, type_recette) VALUES ('Gaufres', 10, 10, 20, 20, 'Dessert');
INSERT INTO Recettes (nom_recette, temps_cuisson_recette, temps_repos_recette, temps_preparation_recette, nombre_parts, type_recette) VALUES ('Crêpes', 4, 60, 10, 30, 'Dessert');
INSERT INTO Recettes (nom_recette, temps_cuisson_recette, temps_repos_recette, temps_preparation_recette, nombre_parts, type_recette) VALUES ('Tiramisu', 0, 60, 10, 4, 'Dessert');
INSERT INTO Recettes (nom_recette, temps_cuisson_recette, temps_repos_recette, temps_preparation_recette, nombre_parts, type_recette) VALUES ('Madeleines au miel', 5, 0, 15, 5, 'Dessert');
INSERT INTO Recettes (nom_recette, temps_cuisson_recette, temps_repos_recette, temps_preparation_recette, nombre_parts, type_recette) VALUES ('Flan', 30, 60, 10, 8, 'Dessert');
INSERT INTO Recettes (nom_recette, temps_cuisson_recette, temps_repos_recette, temps_preparation_recette, nombre_parts, type_recette) VALUES ('Île Flotante', 0, 10, 40, 4, 'Dessert');
INSERT INTO Recettes (nom_recette, temps_cuisson_recette, temps_repos_recette, temps_preparation_recette, nombre_parts, type_recette) VALUES ('Tarte au citron meringuée', 40, 10, 20, 8, 'Dessert');
INSERT INTO Recettes (nom_recette, temps_cuisson_recette, temps_repos_recette, temps_preparation_recette, nombre_parts, type_recette) VALUES ('Opéra', 0, 60, 180, 4, 'Dessert');
INSERT INTO Recettes (nom_recette, temps_cuisson_recette, temps_repos_recette, temps_preparation_recette, nombre_parts, type_recette) VALUES ('Royal', 0, 180, 90, 12, 'Dessert');
INSERT INTO Recettes (nom_recette, temps_cuisson_recette, temps_repos_recette, temps_preparation_recette, nombre_parts, type_recette) VALUES ('Clafouti à la rubarbe', 60, 60, 30, 8, 'Dessert');


-- Remplissage table Ingrédients --

INSERT INTO Ingredients (nom_ingredient, type_ingredient, quantite_ingredient, date_peremption_ingredient, ingredient_preparable) VALUES ('Pâte feuilletée', 'Frais', 50, '2018/12/20', 0);
INSERT INTO Ingredients (nom_ingredient, type_ingredient, quantite_ingredient, date_peremption_ingredient, ingredient_preparable) VALUES ('Oeufs', 'Frais', 200, '2018/12/20', 1);
INSERT INTO Ingredients (nom_ingredient, type_ingredient, quantite_ingredient, date_peremption_ingredient, ingredient_preparable) VALUES ('Crème fraiche', 'Frais', 1000, '2018/12/20', 1);
INSERT INTO Ingredients (nom_ingredient, type_ingredient, quantite_ingredient, date_peremption_ingredient, ingredient_preparable) VALUES ('Oignons', 'Longue conserv', 200, '2019/12/20', 1);
INSERT INTO Ingredients (nom_ingredient, type_ingredient, quantite_ingredient, date_peremption_ingredient, ingredient_preparable) VALUES ('Echalottes', 'Longue conserv', 200, '2019/12/14', 1);
INSERT INTO Ingredients (nom_ingredient, type_ingredient, quantite_ingredient, date_peremption_ingredient, ingredient_preparable) VALUES ('Crabe', 'Surgelé', 50000, '2019/03/14', 1);
INSERT INTO Ingredients (nom_ingredient, type_ingredient, quantite_ingredient, date_peremption_ingredient, ingredient_preparable) VALUES ('Citron', 'Longue conserv', 200, '2019/12/14', 1);
INSERT INTO Ingredients (nom_ingredient, type_ingredient, quantite_ingredient, date_peremption_ingredient, ingredient_preparable) VALUES ('Persil', 'Longue conserv', 200, '2019/12/14', 1);
INSERT INTO Ingredients (nom_ingredient, type_ingredient, quantite_ingredient, date_peremption_ingredient, ingredient_preparable) VALUES ('Piment', 'Longue conserv', 200, '2019/12/14', 1);
INSERT INTO Ingredients (nom_ingredient, type_ingredient, quantite_ingredient, date_peremption_ingredient, ingredient_preparable) VALUES ('Gruyère rapé', 'Frais', 100, '2018/12/20', 0);
INSERT INTO Ingredients (nom_ingredient, type_ingredient, quantite_ingredient, date_peremption_ingredient, ingredient_preparable) VALUES ('Lotte', 'Surgelé', 50, '2019/03/14', 1);
INSERT INTO Ingredients (nom_ingredient, type_ingredient, quantite_ingredient, date_peremption_ingredient, ingredient_preparable) VALUES ('Congre', 'Surgelé', 50, '2019/03/14', 1);
INSERT INTO Ingredients (nom_ingredient, type_ingredient, quantite_ingredient, date_peremption_ingredient, ingredient_preparable) VALUES ('Rouget grondin', 'Surgelé', 50, '2019/03/14', 1);
INSERT INTO Ingredients (nom_ingredient, type_ingredient, quantite_ingredient, date_peremption_ingredient, ingredient_preparable) VALUES ('Seiche', 'Surgelé', 50, '2019/03/14', 1);
INSERT INTO Ingredients (nom_ingredient, type_ingredient, quantite_ingredient, date_peremption_ingredient, ingredient_preparable) VALUES ('Ail', 'Longue conserv', 200, '2019/12/14', 1);
INSERT INTO Ingredients (nom_ingredient, type_ingredient, quantite_ingredient, date_peremption_ingredient, ingredient_preparable) VALUES ('Pomme de terre', 'Longue conserv', 500, '2019/12/14', 1);
INSERT INTO Ingredients (nom_ingredient, type_ingredient, quantite_ingredient, date_peremption_ingredient, ingredient_preparable) VALUES ('Chair à saucisse', 'Frais', 100000, '2018/12/20', 0);
INSERT INTO Ingredients (nom_ingredient, type_ingredient, quantite_ingredient, date_peremption_ingredient, ingredient_preparable) VALUES ('Boeuf', 'Frais', 100000, '2018/12/20', 1);
INSERT INTO Ingredients (nom_ingredient, type_ingredient, quantite_ingredient, date_peremption_ingredient, ingredient_preparable) VALUES ('Tomate', 'Longue conserv', 200, '2019/12/14', 1);
INSERT INTO Ingredients (nom_ingredient, type_ingredient, quantite_ingredient, date_peremption_ingredient, ingredient_preparable) VALUES ('Farine', 'Longue conserv', 200000, '2019/12/14', 0);
INSERT INTO Ingredients (nom_ingredient, type_ingredient, quantite_ingredient, date_peremption_ingredient, ingredient_preparable) VALUES ('Vinaigre', 'Longue conserv', 500, '2019/12/14', 1);
INSERT INTO Ingredients (nom_ingredient, type_ingredient, quantite_ingredient, date_peremption_ingredient, ingredient_preparable) VALUES ('Huile de tournesol', 'Longue conserv', 50, '2019/12/14', 0);
INSERT INTO Ingredients (nom_ingredient, type_ingredient, quantite_ingredient, date_peremption_ingredient, ingredient_preparable) VALUES ('Veau', 'Frais', 50000, '2018/12/20', 1);
INSERT INTO Ingredients (nom_ingredient, type_ingredient, quantite_ingredient, date_peremption_ingredient, ingredient_preparable) VALUES ('Poulet', 'Frais', 50000, '2018/12/20', 1);
INSERT INTO Ingredients (nom_ingredient, type_ingredient, quantite_ingredient, date_peremption_ingredient, ingredient_preparable) VALUES ('Carottes', 'Longue conserv', 200, '2019/12/14', 1);
INSERT INTO Ingredients (nom_ingredient, type_ingredient, quantite_ingredient, date_peremption_ingredient, ingredient_preparable) VALUES ('Vin Blanc', 'Longue conserv', 500, '2019/12/14', 0);
INSERT INTO Ingredients (nom_ingredient, type_ingredient, quantite_ingredient, date_peremption_ingredient, ingredient_preparable) VALUES ('Champignons', 'Longue conserv', 200, '2019/12/14', 1);
INSERT INTO Ingredients (nom_ingredient, type_ingredient, quantite_ingredient, date_peremption_ingredient, ingredient_preparable) VALUES ('Concombre', 'Longue conserv', 200, '2019/12/14', 1);
INSERT INTO Ingredients (nom_ingredient, type_ingredient, quantite_ingredient, date_peremption_ingredient, ingredient_preparable) VALUES ('Huile d''olive', 'Longue conserv', 500, '2019/12/14', 0);
INSERT INTO Ingredients (nom_ingredient, type_ingredient, quantite_ingredient, date_peremption_ingredient, ingredient_preparable) VALUES ('Poivron', 'Longue conserv', 200, '2019/12/14', 1);
INSERT INTO Ingredients (nom_ingredient, type_ingredient, quantite_ingredient, date_peremption_ingredient, ingredient_preparable) VALUES ('Beurre', 'Frais', 50000, '2018/12/20', 0);
INSERT INTO Ingredients (nom_ingredient, type_ingredient, quantite_ingredient, date_peremption_ingredient, ingredient_preparable) VALUES ('Lait', 'Longue conserv', 2000, '2019/12/14', 0);
INSERT INTO Ingredients (nom_ingredient, type_ingredient, quantite_ingredient, date_peremption_ingredient, ingredient_preparable) VALUES ('Sanglier', 'Frais', 50000, '2018/12/20', 1);
INSERT INTO Ingredients (nom_ingredient, type_ingredient, quantite_ingredient, date_peremption_ingredient, ingredient_preparable) VALUES ('Porc', 'Frais', 50, '2018/12/20', 1);
INSERT INTO Ingredients (nom_ingredient, type_ingredient, quantite_ingredient, date_peremption_ingredient, ingredient_preparable) VALUES ('Lardons fumés', 'Frais', 50000, '2018/12/20', 0);
INSERT INTO Ingredients (nom_ingredient, type_ingredient, quantite_ingredient, date_peremption_ingredient, ingredient_preparable) VALUES ('Thon', 'Frais', 50, '2018/12/20', 1);
INSERT INTO Ingredients (nom_ingredient, type_ingredient, quantite_ingredient, date_peremption_ingredient, ingredient_preparable) VALUES ('Thym', 'Longue conserv', 200, '2019/12/14', 1);
INSERT INTO Ingredients (nom_ingredient, type_ingredient, quantite_ingredient, date_peremption_ingredient, ingredient_preparable) VALUES ('Miel', 'Longue conserv', 500, '2019/12/14', 0);
INSERT INTO Ingredients (nom_ingredient, type_ingredient, quantite_ingredient, date_peremption_ingredient, ingredient_preparable) VALUES ('Céleri', 'Longue conserv', 200, '2019/12/14', 1);
INSERT INTO Ingredients (nom_ingredient, type_ingredient, quantite_ingredient, date_peremption_ingredient, ingredient_preparable) VALUES ('Laurier', 'Longue conserv', 200, '2019/12/14', 1);
INSERT INTO Ingredients (nom_ingredient, type_ingredient, quantite_ingredient, date_peremption_ingredient, ingredient_preparable) VALUES ('Amandes', 'Longue conserv', 50000, '2019/12/14', 0);
INSERT INTO Ingredients (nom_ingredient, type_ingredient, quantite_ingredient, date_peremption_ingredient, ingredient_preparable) VALUES ('Persil', 'Longue conserv', 50000, '2019/12/14', 1);
INSERT INTO Ingredients (nom_ingredient, type_ingredient, quantite_ingredient, date_peremption_ingredient, ingredient_preparable) VALUES ('Poireaux', 'Longue conserv', 200, '2019/12/14', 1);
INSERT INTO Ingredients (nom_ingredient, type_ingredient, quantite_ingredient, date_peremption_ingredient, ingredient_preparable) VALUES ('Crevettes', 'Frais', 200, '2018/12/20', 0);
INSERT INTO Ingredients (nom_ingredient, type_ingredient, quantite_ingredient, date_peremption_ingredient, ingredient_preparable) VALUES ('Coriandre', 'Longue conserv', 100, '2019/12/14', 0);
INSERT INTO Ingredients (nom_ingredient, type_ingredient, quantite_ingredient, date_peremption_ingredient, ingredient_preparable) VALUES ('Muscat', 'Longue conserv', 1000, '2019/12/14', 0);
INSERT INTO Ingredients (nom_ingredient, type_ingredient, quantite_ingredient, date_peremption_ingredient, ingredient_preparable) VALUES ('Mouton', 'Frais', 50, '2018/12/20', 1);
INSERT INTO Ingredients (nom_ingredient, type_ingredient, quantite_ingredient, date_peremption_ingredient, ingredient_preparable) VALUES ('Foie Gras', 'Frais', 50, '2018/12/20', 1);
INSERT INTO Ingredients (nom_ingredient, type_ingredient, quantite_ingredient, date_peremption_ingredient, ingredient_preparable) VALUES ('Sucre', 'Longue conserv', 200000, '2019/12/14', 0);
INSERT INTO Ingredients (nom_ingredient, type_ingredient, quantite_ingredient, date_peremption_ingredient, ingredient_preparable) VALUES ('Fenouil sauvage', 'Longue conserv', 200, '2019/12/14', 0);
INSERT INTO Ingredients (nom_ingredient, type_ingredient, quantite_ingredient, date_peremption_ingredient, ingredient_preparable) VALUES ('Biscuits', 'Longue conserv', 1000, '2019/12/14', 1);
INSERT INTO Ingredients (nom_ingredient, type_ingredient, quantite_ingredient, date_peremption_ingredient, ingredient_preparable) VALUES ('Mascarpone', 'Frais', 100000, '2018/12/20', 0);
INSERT INTO Ingredients (nom_ingredient, type_ingredient, quantite_ingredient, date_peremption_ingredient, ingredient_preparable) VALUES ('Cacao', 'Longue conserv', 50000, '2019/12/14', 1);
INSERT INTO Ingredients (nom_ingredient, type_ingredient, quantite_ingredient, date_peremption_ingredient, ingredient_preparable) VALUES ('Café', 'Longue conserv', 600, '2019/12/14', 0);
INSERT INTO Ingredients (nom_ingredient, type_ingredient, quantite_ingredient, date_peremption_ingredient, ingredient_preparable) VALUES ('Levure', 'Longue conserv', 100, '2019/12/14', 0);
INSERT INTO Ingredients (nom_ingredient, type_ingredient, quantite_ingredient, date_peremption_ingredient, ingredient_preparable) VALUES ('Saumon fumé', 'Frais', 50000, '2018/12/20', 1);
INSERT INTO Ingredients (nom_ingredient, type_ingredient, quantite_ingredient, date_peremption_ingredient, ingredient_preparable) VALUES ('Moutarde', 'Frais', 5000, '2019/12/20', 0);
INSERT INTO Ingredients (nom_ingredient, type_ingredient, quantite_ingredient, date_peremption_ingredient, ingredient_preparable) VALUES ('Ciboulette', 'Longue conserv', 200, '2019/12/14', 1);
INSERT INTO Ingredients (nom_ingredient, type_ingredient, quantite_ingredient, date_peremption_ingredient, ingredient_preparable) VALUES ('Gingembre', 'Longue conserv', 200, '2019/12/14', 1);
INSERT INTO Ingredients (nom_ingredient, type_ingredient, quantite_ingredient, date_peremption_ingredient, ingredient_preparable) VALUES ('Soja', 'Longue conserv', 200, '2019/12/14', 1);
INSERT INTO Ingredients (nom_ingredient, type_ingredient, quantite_ingredient, date_peremption_ingredient, ingredient_preparable) VALUES ('Les bonnes pâtes sa mère', 'Longue conserv', 100000, '2019/12/14', 1);
INSERT INTO Ingredients (nom_ingredient, type_ingredient, quantite_ingredient, date_peremption_ingredient, ingredient_preparable) VALUES ('Escargots', 'Frais', 500, '2018/12/20', 1);
INSERT INTO Ingredients (nom_ingredient, type_ingredient, quantite_ingredient, date_peremption_ingredient, ingredient_preparable) VALUES ('Courgette', 'Longue conserv', 200, '2019/12/14', 1);
INSERT INTO Ingredients (nom_ingredient, type_ingredient, quantite_ingredient, date_peremption_ingredient, ingredient_preparable) VALUES ('Pois Chiche', 'Longue conserv', 200, '2019/12/14', 0);
INSERT INTO Ingredients (nom_ingredient, type_ingredient, quantite_ingredient, date_peremption_ingredient, ingredient_preparable) VALUES ('Menthe', 'Longue conserv', 200, '2019/12/14', 1);
INSERT INTO Ingredients (nom_ingredient, type_ingredient, quantite_ingredient, date_peremption_ingredient, ingredient_preparable) VALUES ('Canelle', 'Longue conserv', 200, '2019/12/14', 0);
INSERT INTO Ingredients (nom_ingredient, type_ingredient, quantite_ingredient, date_peremption_ingredient, ingredient_preparable) VALUES ('Huile', 'Longue conserv', 50, '2019/12/14', 0);
INSERT INTO Ingredients (nom_ingredient, type_ingredient, quantite_ingredient, date_peremption_ingredient, ingredient_preparable) VALUES ('Vanille', 'Longue conserv', 200, '2019/12/14', 1);
INSERT INTO Ingredients (nom_ingredient, type_ingredient, quantite_ingredient, date_peremption_ingredient, ingredient_preparable) VALUES ('Rhum', 'Longue conserv', 50, '2019/12/14', 0);
INSERT INTO Ingredients (nom_ingredient, type_ingredient, quantite_ingredient, date_peremption_ingredient, ingredient_preparable) VALUES ('Chocolat', 'Frais', 100000, '2018/12/20', 1);
INSERT INTO Ingredients (nom_ingredient, type_ingredient, quantite_ingredient, date_peremption_ingredient, ingredient_preparable) VALUES ('Rhubarbe', 'Longue conserv', 200000, '2019/12/14', 1);
INSERT INTO Ingredients (nom_ingredient, type_ingredient, quantite_ingredient, date_peremption_ingredient, ingredient_preparable) VALUES ('Sel', 'Longue conserv', 100000, '2019/12/14', 0);
INSERT INTO Ingredients (nom_ingredient, type_ingredient, quantite_ingredient, date_peremption_ingredient, ingredient_preparable) VALUES ('Poivre', 'Longue conserv', 10000, '2019/12/14', 0);
INSERT INTO Ingredients (nom_ingredient, type_ingredient, quantite_ingredient, date_peremption_ingredient, ingredient_preparable) VALUES ('Pain', 'Frais', 500, '2018/12/20', 0);
INSERT INTO Ingredients (nom_ingredient, type_ingredient, quantite_ingredient, date_peremption_ingredient, ingredient_preparable) VALUES ('Navet', 'Longue conserv', 200, '2019/12/14', 1);
INSERT INTO Ingredients (nom_ingredient, type_ingredient, quantite_ingredient, date_peremption_ingredient, ingredient_preparable) VALUES ('Petits pois', 'Longue conserv', 100000, '2019/12/14', 0);
INSERT INTO Ingredients (nom_ingredient, type_ingredient, quantite_ingredient, date_peremption_ingredient, ingredient_preparable) VALUES ('Haricot vert', 'Longue conserv', 100000, '2019/12/14', 0);
INSERT INTO Ingredients (nom_ingredient, type_ingredient, quantite_ingredient, date_peremption_ingredient, ingredient_preparable) VALUES ('Mayonnaise', 'Longue conserv', 1000, '2019/12/14', 0);
INSERT INTO Ingredients (nom_ingredient, type_ingredient, quantite_ingredient, date_peremption_ingredient, ingredient_preparable) VALUES ('Sucre vanillé', 'Longue conserv', 100, '2019/12/14', 0);


-- Remplissage table Composition_Recette --

insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (1, 1, 1);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (1, 2, 2);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (1, 3, 4);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (1, 72, 1);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (1, 73, 1);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (1, 4, 2);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (1, 6, 120);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (1, 7, 1);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (1, 8, 3);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (1, 9, 1);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (2, 2, 4);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (2, 10, 1);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (2, 72, 1);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (2, 73, 1);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (2, 3, 3);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (3, 19, 4);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (3, 4, 2);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (3, 28, 1);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (3, 74, 1);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (3, 29, 10);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (3, 21, 10);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (3, 30, 1);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (3, 72, 1);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (3, 73, 1);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (4, 33, 500);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (4, 17, 250);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (4, 34, 250);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (4, 72, 3);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (4, 73, 1);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (5, 20, 50);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (5, 32, 50);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (5, 27, 6);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (5, 36, 1);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (5, 10, 1);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (5, 1, 1);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (5, 31, 30);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (5, 72, 1);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (5, 73, 1);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (6, 1, 1);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (6, 2, 3);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (6, 3, 30);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (6, 32, 25);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (6, 35, 300);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (6, 10, 1);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (6, 72, 1);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (6, 73,1);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (7, 48, 1);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (8, 27, 12);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (8, 44, 12);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (8, 24, 100);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (8, 25, 4);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (8, 43, 2);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (8, 39, 2);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (8, 45, 1);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (9, 62, 25);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (9, 17, 200);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (9, 34, 250);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (9, 5, 4);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (9, 19, 5);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (9, 15, 4);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (9, 24, 20);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (9, 42, 1);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (9, 50, 1);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (9, 21, 25);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (9, 72, 20);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (9, 73, 1);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (10, 75, 3);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (10, 16, 3);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (10, 25, 3);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (10, 76, 100);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (10, 77, 150);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (10, 2, 1);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (10, 78, 50);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (11, 11, 1);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (11, 12, 1);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (11, 13, 1);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (11, 14, 1);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (11, 6, 1);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (11, 15, 1);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (11, 20, 50);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (11, 72, 3);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (11, 73, 3);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (11, 9, 1);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (11, 16, 3);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (12, 17, 3000);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (12, 18, 1000);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (12, 4, 4);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (12, 15, 2);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (12, 2, 2);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (12, 72, 3);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (12, 73, 3);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (12, 19, 2);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (12, 20, 25);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (12, 22, 10);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (13, 23, 1000);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (13, 25, 3);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (13, 27, 1);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (13, 3, 100);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (13, 7, 1);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (13, 2, 1);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (13, 26, 25);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (14, 34, 500);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (14, 72, 15);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (14, 73, 15);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (14, 10, 1);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (15, 24, 200);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (15, 4, 1);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (15, 21, 10);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (15, 38, 10);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (15, 3, 15);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (15, 29, 10);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (16, 43, 1);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (16, 4, 1);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (16, 15, 1);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (16, 37, 2);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (16, 39, 1);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (16, 40, 1);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (16, 72, 5);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (16, 73, 5);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (16, 35, 250);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (16, 9, 2);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (16, 19, 2);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (16, 15, 2);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (16, 42, 10);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (16, 41, 100);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (16, 26, 10);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (16, 29, 10);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (16, 9, 1);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (17, 29, 10);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (17, 31, 15);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (17, 4, 3);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (17, 24, 20);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (17, 19, 2);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (17, 42, 1);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (17, 72, 3);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (17, 73, 3);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (17, 47, 100);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (17, 45, 1);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (18, 56, 200);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (18, 3, 40);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (18, 58, 1);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (18, 7, 1);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (18, 72, 1);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (18, 73, 1);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (19, 61, 200);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (19, 3, 75);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (19, 35, 50);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (19, 10, 1);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (20, 18, 300);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (20, 61, 100);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (20, 4, 1);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (20, 15, 1);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (20, 19, 10);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (20, 10, 1);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (20, 29, 10);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (20, 31, 90);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (20, 72, 6);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (20, 73, 6);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (20, 20, 70);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (20, 32, 50);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (21, 20, 250);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (21, 2, 3);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (21, 21, 100);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (21, 32, 25);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (21, 49, 75);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (21, 72, 1);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (22, 21, 50);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (22, 20, 250);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (22, 2, 3);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (22, 69, 5);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (23, 2, 3);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (23, 49, 100);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (23, 52, 250);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (23, 51, 24);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (23, 54, 50);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (23, 53, 30);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (24, 31, 125);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (24, 2, 3);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (24, 49, 130);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (24, 38, 10);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (24, 55, 1);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (24, 7, 1);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (24, 72, 3);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (25, 1, 1);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (25, 32, 100);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (25, 49, 160);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (25, 79, 1);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (25, 20, 100);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (25, 68, 1);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (26, 2, 4);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (26, 32, 60);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (26, 68, 1);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (26, 41, 30);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (26, 49, 170);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (26, 7, 5);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (26, 72, 1);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (27, 20, 360);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (27, 21, 125);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (27, 49, 230);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (27, 2, 5);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (27, 72, 1);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (27, 55, 1);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (28, 2, 6);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (28, 49, 310);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (28, 41, 160);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (28, 20, 40);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (28, 31, 150);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (28, 54, 10);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (28, 3, 200);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (28, 70, 200);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (28, 69, 5);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (29, 2, 2);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (29, 49, 60);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (29, 41, 40);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (29, 20, 20);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (29, 31, 30);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (29, 55, 1);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (29, 3, 500);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (29, 70, 300);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (29, 69, 3);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (30, 71, 500);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (30, 49, 150);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (30, 20, 60);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (30, 2, 3);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (30, 3, 200);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (30, 32, 20);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (30, 68, 1);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (30, 49, 20);
insert into Composition_Recette (id_recette, id_ingredient, quantite_ingredient_recette) values (30, 72, 1);


insert into Materiel (nom_materiel, type_materiel, etat_materiel, quantite_materiel) values ('Fourchette', 'Matériel commun', 'Propre', 150);
insert into Materiel (nom_materiel, type_materiel, etat_materiel, quantite_materiel) values ('Fourchette', 'Matériel commun', 'Sale', 0);
insert into Materiel (nom_materiel, type_materiel, etat_materiel, quantite_materiel) values ('Couteau', 'Matériel commun', 'Propre', 150);
insert into Materiel (nom_materiel, type_materiel, etat_materiel, quantite_materiel) values ('Couteau', 'Matériel commun', 'Sale', 0);
insert into Materiel (nom_materiel, type_materiel, etat_materiel, quantite_materiel) values ('Cuillère', 'Matériel commun', 'Propre', 150);
insert into Materiel (nom_materiel, type_materiel, etat_materiel, quantite_materiel) values ('Cuillère', 'Matériel commun', 'Sale', 0);
insert into Materiel (nom_materiel, type_materiel, etat_materiel, quantite_materiel) values ('Cuillère à café', 'Matériel commun', 'Propre', 150);
insert into Materiel (nom_materiel, type_materiel, etat_materiel, quantite_materiel) values ('Cuillère à café', 'Matériel commun', 'Sale', 0);
insert into Materiel (nom_materiel, type_materiel, etat_materiel, quantite_materiel) values ('Cuillère à soupe', 'Matériel commun', 'Propre', 150);
insert into Materiel (nom_materiel, type_materiel, etat_materiel, quantite_materiel) values ('Cuillère à soupe', 'Matériel commun', 'Sale', 0);
insert into Materiel (nom_materiel, type_materiel, etat_materiel, quantite_materiel) values ('Assiette plate', 'Matériel commun', 'Propre', 150);
insert into Materiel (nom_materiel, type_materiel, etat_materiel, quantite_materiel) values ('Assiette plate', 'Matériel commun', 'Sale', 0);
insert into Materiel (nom_materiel, type_materiel, etat_materiel, quantite_materiel) values ('Assiette creuse', 'Matériel commun', 'Propre', 30);
insert into Materiel (nom_materiel, type_materiel, etat_materiel, quantite_materiel) values ('Assiette creuse', 'Matériel commun', 'Sale', 0);
insert into Materiel (nom_materiel, type_materiel, etat_materiel, quantite_materiel) values ('Petite Assiette', 'Matériel commun', 'Propre', 150);
insert into Materiel (nom_materiel, type_materiel, etat_materiel, quantite_materiel) values ('Petite Assiette', 'Matériel commun', 'Sale', 0);
insert into Materiel (nom_materiel, type_materiel, etat_materiel, quantite_materiel) values ('Assiette à dessert', 'Matériel commun', 'Propre', 150);
insert into Materiel (nom_materiel, type_materiel, etat_materiel, quantite_materiel) values ('Assiette à dessert', 'Matériel commun', 'Sale', 0);
insert into Materiel (nom_materiel, type_materiel, etat_materiel, quantite_materiel) values ('Cuitochette', 'Matériel commun', 'Sale', 150);
insert into Materiel (nom_materiel, type_materiel, etat_materiel, quantite_materiel) values ('Cuitochette', 'Matériel commun', 'Propre', 0);
insert into Materiel (nom_materiel, type_materiel, etat_materiel, quantite_materiel) values ('Verre à eau', 'Matériel commun', 'Propre', 150);
insert into Materiel (nom_materiel, type_materiel, etat_materiel, quantite_materiel) values ('Verre à eau', 'Matériel commun', 'Sale', 0);
insert into Materiel (nom_materiel, type_materiel, etat_materiel, quantite_materiel) values ('Verre à vin', 'Matériel commun', 'Propre', 150);
insert into Materiel (nom_materiel, type_materiel, etat_materiel, quantite_materiel) values ('Verre à vin', 'Matériel commun', 'Sale', 0);
insert into Materiel (nom_materiel, type_materiel, etat_materiel, quantite_materiel) values ('Flute de champagne', 'Matériel commun', 'Propre', 150);
insert into Materiel (nom_materiel, type_materiel, etat_materiel, quantite_materiel) values ('Flute de champagne', 'Matériel commun', 'Sale', 0);
insert into Materiel (nom_materiel, type_materiel, etat_materiel, quantite_materiel) values ('Jeu tasse et assiette à café', 'Matériel commun', 'Propre', 50);
insert into Materiel (nom_materiel, type_materiel, etat_materiel, quantite_materiel) values ('Jeu tasse et assiette à café', 'Matériel commun', 'Sale', 0);
insert into Materiel (nom_materiel, type_materiel, etat_materiel, quantite_materiel) values ('Serviette en tissu', 'Matériel commun', 'Propre', 150);
insert into Materiel (nom_materiel, type_materiel, etat_materiel, quantite_materiel) values ('Serviette en tissu', 'Matériel commun', 'Sale', 0);
insert into Materiel (nom_materiel, type_materiel, etat_materiel, quantite_materiel) values ('Nappe', 'Matériel commun', 'Propre', 40);
insert into Materiel (nom_materiel, type_materiel, etat_materiel, quantite_materiel) values ('Nappe', 'Matériel commun', 'Sale', 0);
insert into Materiel (nom_materiel, type_materiel, etat_materiel, quantite_materiel) values ('Caraffe', 'Matériel de restauration', 'Propre', 40);
insert into Materiel (nom_materiel, type_materiel, etat_materiel, quantite_materiel) values ('Corbeille pain', 'Matériel de restauration', 'Propre', 40);
insert into Materiel (nom_materiel, type_materiel, etat_materiel, quantite_materiel) values ('Casserole', 'Matériel de cuisine', 'Propre', 10);
insert into Materiel (nom_materiel, type_materiel, etat_materiel, quantite_materiel) values ('Poêle', 'Matériel de cuisine', 'Propre', 10);
insert into Materiel (nom_materiel, type_materiel, etat_materiel, quantite_materiel) values ('Cuillère en bois', 'Matériel de cuisine', 'Propre', 10);
insert into Materiel (nom_materiel, type_materiel, etat_materiel, quantite_materiel) values ('Bol salade', 'Matériel de cuisine', 'Propre', 5);
insert into Materiel (nom_materiel, type_materiel, etat_materiel, quantite_materiel) values ('Autocuiseur', 'Matériel de cuisine', 'Propre', 2);
insert into Materiel (nom_materiel, type_materiel, etat_materiel, quantite_materiel) values ('Mixeur', 'Matériel de cuisine', 'Propre', 1);
insert into Materiel (nom_materiel, type_materiel, etat_materiel, quantite_materiel) values ('Presse-agrumes', 'Matériel de cuisine', 'Propre', 1);
insert into Materiel (nom_materiel, type_materiel, etat_materiel, quantite_materiel) values ('Tamis', 'Matériel de cuisine', 'Propre', 1);
insert into Materiel (nom_materiel, type_materiel, etat_materiel, quantite_materiel) values ('Entonnoir', 'Matériel de cuisine', 'Propre', 1);
insert into Materiel (nom_materiel, type_materiel, etat_materiel, quantite_materiel) values ('Couteau de cuisine', 'Matériel de cuisine', 'Propre', 5);
insert into Machines (nom_machine, etat_machine) values ('Four', 'Vide');
insert into Machines (nom_machine, etat_machine) values ('Lave-vaisselle', 'Vide');
insert into Machines (nom_machine, etat_machine) values ('Machine à laver', 'Vide');
insert into Machines (nom_machine, etat_machine) values ('Frigo', 'Plein');


